version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: app_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: app_phpmyadmin
    restart: unless-stopped
    depends_on:
        - db
    ports:
      - 8080:80
    environment:
        PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: app_maildev
    restart: unless-stopped
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
    networks:
      - dev

  www:
    build:
      args:
        user: app
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    image: app
    container_name: app_www
    ports:
      - "8000:80"
    volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: unless-stopped
    networks:
        - dev

networks:
  dev:
    driver: bridge
volumes:
  data:

