version: "3.7"
services:
  app:
    build:
      args:
        user: demo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: demo
    container_name: demo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - demo

  adminer:
    image: adminer
    container_name: demo-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - demo 
  db:
    image: mysql:5.7
    container_name: demo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # volumes:
      # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - demo

  nginx:
    image: nginx:alpine
    container_name: demo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - demo

networks:
  demo:
    driver: bridge
